services:
  # flask:
  #   build: .
  #   command: gunicorn -w 2 -b 0.0.0.0:5000 main:app
  #   ports:
  #     - "4000:5000"
  #   volumes:
  #     - ./src/Oil.db:/backend/src/Oil.db
  #   depends_on:
  #     - polling

  # polling:
  #   build: .
  #   command: [ "sh", "-c", "PYTHONUNBUFFERED=1 python poll.py && tail -f /dev/null" ]
  #   volumes:
  #     - ./src/Oil.db:/backend/src/Oil.db

  calc:
    build: .
    command: [ "sh", "-c", "PYTHONUNBUFFERED=1 python calc.py && tail -f /dev/null" ]
    # volumes:
    #   - ./data/prices.db:/backend/data/prices.db