services:
  wtist_devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace
      - ~/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime
    ports:
      - 3000:3000
      - 1337:1337
    shm_size: 2gb
